# -*- coding: utf-8 -*-
"""library.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1czsR9-iLfYHeiwiu2PokSQGF0eDdkKGd
"""

# ============================================
# التصميم الكامل لنظام إدارة المكتبة
# ============================================

import json

# 1️⃣ المتغيرات العامة
# --------------------
library = []  # القائمة الرئيسية
LIBRARY_FILE = "library.json"

# 2️⃣ دوال التحقق من المدخلات
# ----------------------------
def get_valid_number(prompt):
    while True:  # حلقة للتكرار
        try:
            num = int(input(prompt))
            if num > 0:  # شرط: موجب
                return num
            print("❌ أدخل رقماً موجباً")
        except ValueError:  # معالجة الخطأ
            print("❌ أدخل رقماً صحيحاً")

def get_non_empty_string(prompt):
    while True:  # حلقة للتكرار
        text = input(prompt).strip()
        if text:  # شرط: غير فارغ
            return text
        print("❌ الحقل مطلوب")

# 3️⃣ دوال الملفات
# -----------------
def save_library(lib):
    try:
        with open(LIBRARY_FILE, "w", encoding="utf-8") as f:
            json.dump(lib, f, ensure_ascii=False, indent=2)
        print("💾 تم الحفظ")
    except Exception as e:
        print(f"❌ خطأ: {e}")

def load_library():
    try:
        with open(LIBRARY_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return []  # مكتبة فارغة

# 4️⃣ دوال العمليات
# ------------------
def add_book(lib):
    print("\n📝 إضافة كتاب")
    title = get_non_empty_string("العنوان: ")
    author = get_non_empty_string("المؤلف: ")
    year = get_valid_number("السنة: ")
    copies = get_valid_number("النسخ: ")

    lib.append({
        "title": title,
        "author": author,
        "year": year,
        "copies": copies
    })
    print("✅ تمت الإضافة")

def display_books(lib):
    if not lib:  # شرط: فارغة؟
        print("\n📭 المكتبة فارغة")
        return

    print("\n📚 الكتب:")
    for i, book in enumerate(lib, 1):  # حلقة مع ترقيم
        print(f"{i}. {book['title']} - {book['author']}")

def search_books(lib):
    term = input("\n🔍 ابحث: ").lower()
    results = [b for b in lib if term in b["title"].lower()]

    if results:  # شرط: هل وُجدت نتائج؟
        for book in results:  # حلقة للعرض
            print(f"📖 {book['title']}")
    else:
        print("❌ لا نتائج")

# 5️⃣ القائمة الرئيسية
# --------------------
def main_menu():
    global library
    library = load_library()  # تحميل عند البداية

    while True:  # حلقة رئيسية
        print("\n" + "="*30)
        print("1. إضافة | 2. عرض | 3. بحث | 4. خروج")
        choice = input("اختر: ")

        if choice == "1":
            add_book(library)
        elif choice == "2":
            display_books(library)
        elif choice == "3":
            search_books(library)
        elif choice == "4":
            save_library(library)  # حفظ قبل الخروج
            print("👋 وداعاً")
            break
        else:
            print("❌ خيار خاطئ")

# 6️⃣ تشغيل البرنامج
# -------------------
if __name__ == "__main__":
    main_menu()

